version: '3'
services:
  frontend:
    image: frontend-app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./work-with-users_backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:12345678@db:5432/work_with_users
      PORT: 5000
      SWAGGER_SERVER_URL: http://localhost:5000
    volumes:
      - ./work-with-users_backend:/app
      - /app/node_modules
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: work_with_users
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
